### ISSUE TITLE
Convert state entity arrays to records

### ISSUE THREAD

**Issue by Predjo** [Predjo/redux-observable-demo-app#21]
[TodoStateItem, TodoStateItem] => { id: TodoStateItem, id2: TodoStateItem }

**Comment by vbradvica** [comment]
Model state as below: 

```
state = {
  users: {
    entities: {
      vinko@vinko.com: {
        email: 'vinko@vinko.com',
        todos: [4,7,17],
      }
    }
  },
  todos: {
    loading: {
      pages: {
        0: {
          index: 0,
          nextPage: 1,
          items: [0, 1, 2],
        },
        1: {
          index: 0,
          nextPage: 1,
          items: [3, 4, 5],
        }
      }
    },
    entities: {
      0: {},
      1: {},
      2: {},
      3: {},
      4: {},
      5: {},
      7: {},
      17: {},
    }
  }
}
```

Every TodoItem that is loaded is added to the `state.todos.entities`. The source of these items can be from multiple sourcer - paginated todo views or user's todo items.

The parent items will reference entities by ID. 
`state.todos.loading.pages[0].items = [0, 1, 2]`
`state.users.entities['vinko@vinko.com'].todos = [4, 7, 17]`
