### ISSUE TITLE
AppState type

### ISSUE THREAD

**Issue by markotron** [Predjo/redux-observable-demo-app#4]
We should calculate the AppState type rather than define it. Currently, we have: 

```
declare global {
  export interface AppState {
    todos: TodoState;
  }
}
```

This implies that for every slice we'd have to add a state here. We should do something like: 
```
type AppState = ReturnType<typeof rootReducer>
```
where `rootReducer = combineReducers({...})`

**Comment by Predjo** [comment]
Yap already have this in plan. Added in the PR.
