### ISSUE TITLE
State epics

### ISSUE THREAD

**Issue by markotron** [Predjo/redux-observable-demo-app#5]
As we only wish to use epics that react on state we can add a helper function that will allow us to remove the action argument. 
```
const stateEpic = (state: Observable<AppState>) => state.pipe(...)
```
we could create the `toEpic` extension on a `ReturnType<typeof stateEpic>` that will automatically add a dummy first parameter. Usage would be like this: 

```
export default combineEpics(
  loadTodosEpic.toEpic(),
  updateTodoEpic.toEpic(),
  addTodoEpic.toEpic(),
  removeTodoEpic.toEpic()
);
```
and loadTodosEpic wouldn't have the first argument.

**Comment by markotron** [comment]
`toEpic` would look like: 

`return (_: Observable<PayloadAction<any>, state: Observable<AppState>) => this(state)`.

`this` is a `stateEpic` in this case.

**Comment by Predjo** [comment]
Done with a slight twist.
