### ISSUE TITLE
Another component

### ISSUE THREAD

**Issue by markotron** [Predjo/redux-observable-demo-app#6]
Add another component (or 2) so that we can see how combining slices and app state type works in practice. The components should communicate.. if possible (or desireable?) one component could call actions from another.

**Comment by Predjo** [comment]
What exactly do you mean by actions from a component? Since we are using Redux all actions are global so they can be used from anywhere.

**Comment by markotron** [comment]
Nothing special. Just that we need a different component with its state to see how they work together in terms of type...
